# Generated by Django 3.2.1 on 2022-04-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_image_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_type',
            field=models.CharField(blank=True, choices=[('Newly Released', 'Newly Released'), ('Coming Soon', 'Coming Soon')], max_length=50, verbose_name='release_type'),
        ),
    ]
